{% set name = "mmsegmentation" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mmsegmentation-{{ version }}.tar.gz
  sha256: 35338c089e0342a4c80d446763bd8cd31641e9c430de495611c966a2131fd489

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - mmcv
    - numpy
    - py-opencv
    - packaging
    - prettytable
    - python >=3.7
    - scipy

test:
  imports:
    - mmseg
  commands:
    - pip check
    - python -c "import mmseg; print(mmseg.__version__)"
  requires:
    - pip

about:
  home: http://github.com/open-mmlab/mmsegmentation
  summary: Open MMLab Semantic Segmentation Toolbox and Benchmark
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mmsegmentation.readthedocs.io

extra:
  recipe-maintainers:
    - weiji14
